Create months
NOTE: that we export an object here b/c it will
provide two functions. testdouble.js is smart 
enough to pick up on this and create a  `td.object()`

Changed the message:
---
Error: Cannot find module '/Users/justin/code/testdouble/unusual-spending-kata/lib/wrapper/payment-api'
    at Function.Module._resolveFilename (module.js:336:15)
    at doWithoutCache (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/testdouble/node_modules/quibble/lib/quibble.js:94:23)
    at Function.fakeLoad [as _load] (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/testdouble/node_modules/quibble/lib/quibble.js:73:14)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports [as replace] (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/testdouble/lib/replace.js:20:17)
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/test/lib/fetch-payments-test.js:5:23)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:47:9
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)