Define `months.lastMonth()`
Just like with `months.thisMonth()`, defining the function will send
the cue to testdouble.replace to create a function test double.

Changed the message:
---
AssertionError: undefined deepStrictEqual { thisMonth: 'this month payments',
  lastMonth: 'last month payments' }
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/test/lib/fetch-payments-test.js:16:10)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:47:9
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:43:7
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:41:5)
    at Object.<anonymous> (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/bin/teenytest:7:15)
    at Module._compile (module.js:434:26)