Write the first failing test
message:
---
Error: Cannot find module '/Users/justin/code/testdouble/unusual-spending-kata/lib/fetch-payments'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.module.exports [as replace] (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/testdouble/lib/replace.js:20:17)
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/test/lib/unusual-spending-test.js:2:26)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:47:9
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:43:7