Write third failing test of months.thisMonth
Note that this test DOES NOT use testdouble.js, because it's a logical
leaf node in our tree of functionality. It does not have any 
collaborators; it just has its own behavior to worry about.

As a result, we write a perfectly normal humdrum test that validates
its intrinsic behavior.

Message:
---
AssertionError: undefined deepStrictEqual { year: 2016, month: 2 }
    at module.exports.thisMonthIsThisMonth (/Users/justin/code/testdouble/unusual-spending-kata/test/lib/months-test.js:10:12)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:47:9
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:43:7
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:41:5)
    at Object.<anonymous> (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/bin/teenytest:7:15)
    at Module._compile (module.js:434:26)