Implement a wrapper for the payment-api
We do this for a few reasons instead of faking out the npm module itself

"Don't mock what you don't own"; TDD is about getting design feedback 
and responding to it; since we don't own the payment-api, we can't 
respond to any test pain we experience by improving its API. 

Changed the message:
---
TypeError: months.thisMonth is not a function
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/test/lib/fetch-payments-test.js:9:18)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:47:9
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at /Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:43:7
    at arrayEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/node_modules/lodash/lodash.js:7607:11)
    at module.exports (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/index.js:41:5)
    at Object.<anonymous> (/Users/justin/code/testdouble/unusual-spending-kata/node_modules/teenytest/bin/teenytest:7:15)
    at Module._compile (module.js:434:26)